### ISSUE TITLE
Potential dangling reference in example

### ISSUE THREAD

**Issue by sweet2honey** [dpuyda/scheduling#35]
Hi Dmytro, thanks for you work. I've learnt a lot from your paper introducing the library.

Here's something i found that may mislead users when using:

https://github.com/dpuyda/scheduling/blob/998beb3526e40d8d9cd29797d4994bdfa6f7c076/README.md?plain=1#L144

You use a temp variable to refer to the last emplaced element, but notice that, for `std::vector<T,Allocator>::emplace_back`
> If after the operation the new [size()](https://en.cppreference.com/w/cpp/container/vector/size) is greater than old [capacity()](https://en.cppreference.com/w/cpp/container/vector/capacity) a reallocation takes place, in which case all iterators (including the [end()](https://en.cppreference.com/w/cpp/container/vector/end) iterator) and all references to the elements are invalidated.

If user offers more elements than the vector's default capacity, a reallocation may invalid the temp variables i suppose.
Thus later `.Succeed` oprations may result in UB.

**Comment by dpuyda** [comment]
Thank you very much for your attention to this, @sweet2honey! I have already updated the README file with an important note about [reserving](https://en.cppreference.com/w/cpp/container/vector/reserve) the space for tasks, please see issue https://github.com/dpuyda/scheduling/issues/33 and pull request https://github.com/dpuyda/scheduling/pull/34 for the reference.

As I mentioned in the comment to Issue #33, you can either use `std::vector` and `reserve` as shown in the example, or use `std::vector` without `reserve` and reference tasks by indices, or use a container which does not reallocate elements. I personally would recommend using `std::vector` and `reserve` because other options are less convenient (like referencing the tasks by indices) or less efficient (like non-sequential memory allocation). You can also check [unit tests](https://github.com/dpuyda/scheduling/blob/main/tests/thread_pool_test.cpp) for the reference. Typically, we would create a simple class wrapper for a task graph to wrap an `std::vector` of tasks and the shared state, and call `reserve` before adding the tasks in the constructor.

Please accept my apologies for not mentioning this in the README file earlier, and thanks a lot for your interest in the project!

**Comment by sweet2honey** [comment]
Thank you!

It seems that the readme file was updated like a week ago. I came from the paper thus I thought I missed some part of the updated version.

I will check out the unit tests for more information 😃

**Comment by dpuyda** [comment]
@sweet2honey, yeah, I realized that I hadn’t mentioned reserve in the README when issue #33 was opened. I’ll need to include this in the paper as well, in case it gets published. Thanks for catching that!

I’ll close this issue if you don’t mind, as it seems clarified. Please feel free to reach out if you have any questions. Thank you!
